/*
 * Automatically generated C config: don't edit
 * Fri May 10 19:58:00 2013
 */
#define UCONFIG_DRAM_START 0x0
#define UCONFIG_ARM_CPU_V7 1
#define UCONFIG_ARCH "arm"
#define UCONFIG_BIONIC_LIBC 1
#define UCONFIG_SCHEDULER_MLFQ 1
#define UCONFIG_ADDITIONAL_LDFLAGS ""
#define UCONFIG_KERNEL_BASE 0x10000
#define UCONFIG_SFS_IMAGE_SIZE 200
#define UCONFIG_DDE_EXAMPLE_CHRDEV 1
#define UCONFIG_ARM_BOARD_GOLDFISH 1
#define UCONFIG_DDE_GOLDFISH_EVENT 1
#define UCONFIG_DDE_GOLDFISH_FB 1
#define UCONFIG_HAVE_SFS 1
#define UCONFIG_RAMDISK_FILE "sfs.img"
#define UCONFIG_HAVE_RAMDISK 1
#define UCONFIG_HEAP_SLAB 1
#define UCONFIG_DDE_MMC_SUPPORT 1
#define UCONFIG_DDE_MMC_UCORE_BLOCK 1
#define UCONFIG_DDE_GOLDFISH_MMC 1
#define UCONFIG_HAVE_LINUX_DDE_BASE 1
#define UCONFIG_DRAM_SIZE 0x10000000
#define UCONFIG_UNAME_RELEASE "3.5.0-23-generic"
#define UCONFIG_ADDITIONAL_CFLAGS "-g -ggdb"
#define UCONFIG_FPU_ENABLE 1
#define UCONFIG_CROSS_COMPILE "arm-eabi-"
#define UCONFIG_HAVE_FATFS 1
